### PR TITLE
add checkbox to codesandbox-ci

### PR DESCRIPTION
**Pull request by chancestrickland**

### CODE REVIEW

**Comment by chancestrickland** [comment]
@hipstersmoothie Opened this branch/PR to continue working on the Codesandbox CI issue. Not a huge priority at the moment, but if you have any other ideas feel free to suggest. Appreciate you getting started on this!

**Comment by hipstersmoothie** [comment]
I’ve contacted the guy who runs codesandbox on twitter and he said he’ll
take a look tomorrow!

**Comment by CompuIves** [comment]
Hey! I have written a fix to respect the topological order of packages in CI. It will be deployed today!

**Comment by CompuIves** [comment]
Well, as you can see, the fix has been deployed!

**Comment by CompuIves** [comment]
By the way, I found your example sandbox super interesting. If you would like to talk about how we can improve CodeSandbox CI for your flow please send a message to ives@codesandbox.io. I'm also looking at ways we can combine/sync Storybook with CodeSandbox CI repros, that would be super interesting.

**Comment by chancestrickland** [comment]
@CompuIves Absolutely, you'll hear from me soon! Thanks a ton for the super quick fix, and thank you @hipstersmoothie for bringing this to their attention.

**Pull request merged**
