### PR TITLE
Breadcrumb: first draft

### PR DESCRIPTION
**Pull request by siddharthkp**
- [x] Added new component
- [x] Added docs (kind of)
- [x] Added stories
- [ ] Write some tests you bum
- [ ] Added types

I have added the documentation but it's not fully functional because `www` is not part of the lerna setup(?), it expects a component to be published to the registry first.

This was a lot of fun to build, I really like how to project is built and optimises for making contributions easier.

**Documented my implementation notes in: [notes.md](https://github.com/reach/reach-ui/compare/master...siddharthkp:breadcrumb?expand=1#diff-4505d08886242bfca68bc1c0995242e6), it's easier to have a discussion on the diff**

--- 

Repo level things I did not understand:

- We add `index.js` in `.eslintignore` for every package, seems like a strange move.
- Is there a specific order that you folks in the documentation for a component? I tried to replicate what I saw

### CODE REVIEW

**Comment by siddharthkp** [comment]
@ryanflorence @mjackson Hi :wave:

**Comment by tarang9211** [comment]
@siddharthkp need help on this?

**Comment by siddharthkp** [comment]
🤷‍♀

**Comment by chancestrickland** [comment]
@siddharthkp Sorry about the confusion, would you mind rebasing your branch on our master branch when you get a chance so I can review? The history got a little messed up it seems.

**Pull request closed without merging**
