### PR TITLE
@reach/tooltip - Change leaving time

### PR DESCRIPTION
**Pull request by eng-almeida**
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more quickly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code (Compile and run).
- [ ] Add or edit tests to reflect the change (Run with `yarn test`).
- [ ] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [ ] Ensure formatting is consistent with the project's Prettier configuration.

This pull request:

- [ ] Creates a new package
- [ ] Fixes a bug in an existing package
- [ ] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [x] Other

If creating a new package:

- [ ] Make sure the new package directory contains each of the following, and that their structure/formatting mirrors other related examples in the project:
  - [ ] `examples` directory
  - [ ] `src` directory with an `index.js` entry file
  - [ ] Type definitions in an `index.d.ts` file are desired but not required for the PR to be merged
  - [ ] At least one example file per feature introduced by the new package
  - [ ] Base styles in a `style.css` file (if needed by the new package)

## Tooltip: Update leaving time

The intent of this PR is to standardize the tooltip visible leaving time with the [entering time](https://github.com/reach/reach-ui/blob/master/packages/tooltip/src/index.js#L201).

### CODE REVIEW

**Comment by chancestrickland** [comment]
@eng-almeida Can you explain your rationale a bit more? What is the argument over choosing a 100ms delay vs. a 500ms delay? Is this an arbitrary preference or is there precedent for this choice that we've missed?

**Comment by eng-almeida** [comment]
@chancestrickland I should have put a better description on the PR description, sorry about that.
As it is right now there are 2 different timer values, 100 ms for the enter event and 500 ms for the leave event. Is this the intended behaviour? Wouldn't make sense to use the same value? Also isn't 500 ms a bit too much?

**Comment by chancestrickland** [comment]
Personally I feel like it makes sense to have the tooltip stick around a bit longer on exit. If you don't quite rest the cursor steadily at first, it gives the user a small opportunity to correct without seeing a flicker. There doesn't appear to be a standard here, and I'm opening to exposing props for a bit more control here.

**Comment by chancestrickland** [comment]
I'm going to close this for now per my comment here: https://github.com/reach/reach-ui/issues/411#issuecomment-573970811

We may revisit this after the 1.0 release and a subsequent audit from WebAIM, but I don't want to introduce any changes here without better guidance on the accessibility impact.

**Pull request closed without merging**
