### PR TITLE
Opening external links in new tab

### PR DESCRIPTION
**Pull request by olezhek85**
Added target attribute to open Spectrum Community and GitHub links in new tab.

### CODE REVIEW

**Comment by olezhek85** [comment]
Added.

**Comment by ryanflorence** [comment]
Any reason people can't just hold command or control and click the link? What's the justification for opening in a new window?

**Comment by MaxymSemenykhin** [comment]
> Any reason people can't just hold command or control and click the link?
 Why I as user should press control if it's obviously should be an external link in new tab?

For example https://reactjs.org/ bootom links 

image


They all contain `target="_blank" ` , so for me as regular user it is obviously that those links should have`target="_blank"` any valid arguments that they shouldn't?

**Comment by olezhek85** [comment]
It's a common practice to open external links in a new tab, isn't it?

**Comment by ryanflorence** [comment]
I've never known how to decide these things, but there are two confetti emojis on the last comment so that's enough for me 😂

**Pull request merged**
