### PR TITLE
chore: Upgrades all packages incl storybook

### PR DESCRIPTION
**Pull request by maraisr**
With this PR I address a few things, despite not being perfect, it's a start at some iteration... 

I address:

- Upgraded storybook to v5
- Upgraded babel to v7
- Upgraded jest to v24
- Switched to yarn workspaces over lerna bootstrap (happy to revert this guy)

The new `jest.config.js` is simply there to give the terminal some character, however, it's not needed. As the `projects` property doesn't require it being there. (probably use a plopfile file this?)

Furthermore, AFAIK storybook runs in the cwd of the command, and since that cwd has a babel config, the webpack for storybook should read that, and the _new_ storybook already handles .css files, and a simple postcss prop on package.json will allow plugins to be added.

- [ ] add the current postcss plugins back in (🤦‍♂️)

fixes: #123

### CODE REVIEW

**Comment by maraisr** [comment]
@ryanflorence this one would be a good one to get merged 💯

**Comment by chancestrickland** [comment]
Closing this for now, as we've made a lot of updates to the build and dependencies across the board that should take care of the issues here. Feel free to open a new issue or PR if there's something you feel like we missed!

**Comment by maraisr** [comment]
That's okay - probably should have been merged when it was created. But that's okay, sorry for wasting your time. :)

**Comment by chancestrickland** [comment]
@maraisr No time wasted, thank you for contributing! I'm new on the project and dedicated to Reach UI. We've gotten pretty far behind on addressing issues and PRs and are actively trying to change that, so please don't let that discourage you from contributing in the future!

**Pull request closed without merging**
