### PR TITLE
menu-button(fix): fix selection when assistive tech on

### PR DESCRIPTION
**Pull request by mezzab**
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more quickly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code (Compile and run).
- [ ] Add or edit tests to reflect the change (Run with `yarn test`).
- [ ] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [x] Ensure formatting is consistent with the project's Prettier configuration.
- [ ] Add documentation to support any new features.

This pull request:

- [ ] Creates a new package
- [x] Fixes a bug in an existing package
- [ ] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [ ] Other

Issue:
Info about the problem here: https://github.com/reach/reach-ui/issues/805

Solution:
`mousemove` event is not being called because of the assistive technology, my suggestion is to use `onfocus` for these cases.

### CODE REVIEW

**Comment by mezzab** [comment]
Tested in iPhone 11 | iOS 14.5.1 
https://user-images.githubusercontent.com/7173948/121404977-e1df7d00-c932-11eb-9ba1-ab2dba7bcf8b.mp4

And in Pixel 4a 5g | Andriod 11

**Comment by wsong-indeed** [comment]
How much longer do we expect this CR to take?

**Comment by chaance** [comment]
Sorry for the backlog here, haven't had a ton of time for OSS the past few weeks but I'm reviewing this today.

**Comment by powerOFMAX** [comment]
I'm having exactly the same issue.  Any updates on this? 🤔

**Comment by mezzab** [comment]
@chaance almost a month from open, do you think they can prioritize this PR?

**Comment by indiesquidge** [comment]
Please understand that this library does not currently have full-time support right now. In fact, it's practically just Chance running the whole thing. Given that, and the fact that Chance is doing this entirely for free and on his own time, there should be no SLA expectations or obligations on what people think should be prioritized and merged.

Keep in mind that you can always patch this behavior in the mean time in your own code with https://www.npmjs.com/package/patch-package

**Pull request merged**
