### PR TITLE
Fix menu button hover in IE 11 (fixes #201)

### LINKED ISSUE #201: MenuButton disappears when hover all but first child [IE 11]
Thanks to #181 the MenuButton displays in the correct place in IE 11, but if I hover over a MenuItem past the first child, it disappears:

L1iHHoaULY

This appears to be because within the `onBlur` handler, `event.relatedTarget` is `null`:

screenshot-1

Version: MenuButton 0.1.18

### PR DESCRIPTION
**Pull request by rebolyte**

### CODE REVIEW

**Comment by alistairjcbrown** [comment]
Confirmed that this fixes the issue for me

reach-ui-menu-button

**Comment by liamjohnston** [comment]
Can this be merged in...? 🙏 @rebolyte @JohnnyMcFadden

**Comment by mikecousins** [comment]
Any chance you can merge this in @mjackson ?

**Comment by alistairjcbrown** [comment]
Hey @mjackson, great to see you updating this repo;  just hoping this PR might be able to be up your list of changes to land - it'd be really great to get IE11 support back into the component, thanks! 🙇

**Comment by chancestrickland** [comment]
@alistairjcbrown @mikecousins We're playing (quite a bit of) catch up on old PRs and issues, and I believe this may have been similar to one we already merged. Can either of you test from the latest on master and let me know if the issue persists? I will be building and releasing updates by the end of the week, so I'll check back and test the fix myself if you are both still experiencing this bug.

**Comment by chancestrickland** [comment]
Double checked, and this should be addressed in https://github.com/reach/reach-ui/pull/110. Closing for now!

**Comment by mikecousins** [comment]
Thanks Chance.

**Pull request closed without merging**
