### PR TITLE
MenuButton: fixing null focus issue on menu button

### PR DESCRIPTION
**Pull request by kendallgassner**
resolving:
https://github.com/reach/reach-ui/issues/194

Testing menu button using jest/react-testing-library causes a null focus error.  In the test requestAnimationFrame is called before the refs.items array has been filled with nodes. If the refs.items list is empty we should not try and focus on the null/undefined element.

### CODE REVIEW

**Comment by venikx** [comment]
Sounds like this is fixed with this PR: https://github.com/reach/reach-ui/pull/241

**Comment by kendallgassner** [comment]
@venikx unfortunately #241  does not fix my problem. In my tests I have children. It is just that the refs to the children have not finished been added to the ref.items list at the time that the first animationFrame has been called.

**Comment by venikx** [comment]
@kendallgassner Thanks for checking it out and fast feedback, since I’mcurrently on holiday so I couldn’t verify it myself! 
Too bad, but I was kinda expecting it, since I didn’t really test with requestAnimationFrame. Awesome! 🎉

**Comment by mjackson** [comment]
Can you please back out the changes to `yarn.lock` from this PR? Otherwise, we can go ahead and merge.

**Comment by tylerkrupicka** [comment]
@mjackson can you take a look at this again?

**Pull request merged**
