### PR TITLE
[@reach/tooltip] Change types to also allow using SVG elements

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there! 👋 Thanks for Reach UI!

I just wanted to add this types change which is necessary to use the exported `TriggerParams` generic type with `SVGSVGElement`, eg. when using the tooltip with an `<svg>` element as a child.

Without this change, TypeScript displays errors such as:

```
Type 'SVGSVGElement' does not satisfy the constraint 'HTMLElement'.
  Type 'SVGSVGElement' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 20 more.ts(2344)
```

Screen Shot 2022-06-12 at 13 33 06

Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more quickly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code (Compile and run).
- [ ] Add or edit tests to reflect the change (Run with `yarn test`).
- [ ] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [ ] Ensure formatting is consistent with the project's Prettier configuration.
- [ ] Add documentation to support any new features.

This pull request:

- [ ] Creates a new package
- [x] Fixes a bug in an existing package
- [ ] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [ ] Other

If creating a new package:

- [ ] Make sure the new package directory contains each of the following, and that their structure/formatting mirrors other related examples in the project:
  - [ ] `examples` directory
  - [ ] `src` directory with an `index.tsx` entry file
  - [ ] At least one example file per feature introduced by the new package
  - [ ] Base styles in a `style.css` file (if needed by the new package)

### CODE REVIEW

**Comment by karlhorky** [comment]
@chaance thanks for merging! Will this be released in `@reach/tooltip` version `0.17.1` or `0.18.0` soon?

**Comment by chaance** [comment]
@karlhorky As time allows. This is a very part-time project for me so no ETA, but I'll get a new release out as soon as I can.

**Comment by karlhorky** [comment]
Ok, thanks, let's see when it gets published then :)

**Comment by karlhorky** [comment]
Or @chaance, is there anyone else who can publish a new release? Would be cool to get this out there and remove my patch :)

**Pull request merged**
