### PR TITLE
import react as an esmodule and turn off allowSyntheticDefaultImports

### PR DESCRIPTION
**Pull request by hipstersmoothie**
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more quickly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code (Compile and run).
- [x] Ensure formatting is consistent with the project's Prettier configuration.

This pull request:

- [x] Fixes a bug in an existing package

This typescript config option make it so that consumer **must** also set these settings. [Read more from a core typescript member here](https://github.com/quilljs/delta/pull/34#issue-232142412).

I found that these two options killl typechecking performance.

All imports of react are like

```js
import * as React from 'react';
```

[This is the suggested way by the core react team](https://twitter.com/sebmarkbage/status/1250284377138802689?lang=en)

The one place I couldn't get it to work was with ts-node. [This is a known limiation](https://www.npmjs.com/package/ts-node#import-statements). So for the build scripts they still run with `allowSyntheticDefaultImports`

---

# The Important Parts

1. Turn off `allowSyntheticDefaultImports` and `esModuleInterop` https://github.com/reach/reach-ui/pull/614/files#diff-17d19956339a21e53394cda05f5a6cc3
2. Turn on `esModuleInterop` in tooling tsconfig (test, lint, storybook, editor) https://github.com/reach/reach-ui/pull/614/files#diff-e5e546dd2eb0351f813d63d1b39dbc48
3. Rename all package's `tsconfig.build.json` to `tsconfig.json` so editor will respect setting for package
4. Change build script in each package to use root `tsconfig.json` to run `ts-node`
5. Modify a bunch of code to import modules in a slightly different way

## Result

- User no longer *needs* to configure `allowSyntheticDefaultImports` or `esModuleInterop`
- VSCode (and other editors) correctly report importing modules in the wrong way

### CODE REVIEW

**Comment by chancestrickland** [comment]
Hey @hipstersmoothie I've actually been looking at this. What was your reasoning for closing the PR?

**Comment by hipstersmoothie** [comment]
I closed it because it would be a pretty big breaking change. Without `esModuleInterop` default exports are harder to use in babel project.

But if we did 2 breaking changes at the same time it would probably be okay:

1. turn off `esModuleInterop` and `allowSyntheticDefaultImport`
2. deprecate all default exports in favor of named exports

**Comment by chancestrickland** [comment]
Cool, appreciate you getting this started. I'll investigate further 👍

**Comment by hipstersmoothie** [comment]
The hardest part of this was getting the ts-node build scripts to work without esModuleInterop because of how some of the rollup plugins work

**Pull request closed without merging**
