### PR TITLE
As prop accordian

### PR DESCRIPTION
**Pull request by Jarvis1010**
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more quickly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code (Compile and run).
- [x] Add or edit tests to reflect the change (Run with `yarn test`).
- [x] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [x] Ensure formatting is consistent with the project's Prettier configuration.

This pull request:

- [ ] Creates a new package
- [ ] Fixes a bug in an existing package
- [x] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [ ] Other

If creating a new package:

- [ ] Make sure the new package directory contains each of the following, and that their structure/formatting mirrors other related examples in the project:
  - [ ] `examples` directory
  - [ ] `src` directory with an `index.js` entry file
  - [ ] Type definitions in an `index.d.ts` file are desired but not required for the PR to be merged
  - [ ] At least one example file per feature introduced by the new package
  - [ ] Base styles in a `style.css` file (if needed by the new package)

This PR is in reference to #459

### CODE REVIEW

**Comment by chancestrickland** [comment]
I'll take a look at this either today or early next week, but just a quick note that the types won't work with the code as-is. Take a look at other components that use the `as` prop to see how we handle those a little differently to get the type defs right.

**Comment by Jarvis1010** [comment]
I will look at the other types and update it as well.  Thank you for the help

**Comment by chancestrickland** [comment]
Added in 0.8.2. Thanks again!

**Comment by Jarvis1010** [comment]
Thank you for opportunity

**Pull request closed without merging**
