### PR TITLE
chore: react 17 compatibility for all packages

### LINKED ISSUE #695: Bump react and react-dom peerDependencies version
### Current Behavior

Peer dependency warnings are generated when installing reach-ui libs using React 17:

```
warning @reach/portal@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning @reach/portal@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning @reach/tooltip@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning @reach/tooltip@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
```

### Expected behavior

No warnings.

### Suggested solution(s)

Change peer dependencies to "react@^16.8.0 || react@^17.0.0"

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | many (all?)        | latest        |
| React            |         | 17.0.1        |

### PR DESCRIPTION
**Pull request by TimKolberger**
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more quickly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code (Compile and run).
- [x] Add or edit tests to reflect the change (Run with `yarn test`).
- [ ] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [x] Ensure formatting is consistent with the project's Prettier configuration.
- [ ] Add documentation to support any new features.

This pull request:

Closes #695

- [ ] Creates a new package
- [ ] Fixes a bug in an existing package
- [ ] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [x] Other

I updated deps and peerDeps of react, react-dom and testing utils to allow react versions greater than 17.

### CODE REVIEW

**Comment by TimKolberger** [comment]
Just saw #701 :eyes:
I did not encounter any issues after upgrading the testing lib deps.

**Comment by felixmosh** [comment]
Can i be reviewed & merged pls?

**Comment by davibarreira** [comment]
This feature would be great!

**Comment by karlhorky** [comment]
@TimKolberger you can add a note in your issue description above that this "Closes #695" - this will cause GitHub to link and close the related issue.

**Comment by tannerhuynh** [comment]
Is this not available in 0.15.0?

**Pull request merged**
