### PR TITLE
[rect] Consider observe variable before throwing warning

### PR DESCRIPTION
**Pull request by afzalsayed96**
Would it make more sense to check if `observe` is set to `true` before the `console.warn("You need to place the ref")`?

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code (Compile and run).
- [ ] Add or edit tests to reflect the change (Run with `yarn test`).
- [ ] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [ ] Ensure formatting is consistent with the project's Prettier configuration.

This pull request:

- [ ] Creates a new package
- [ ] Fixes a bug in an existing package
- [ ] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [x] Other

### CODE REVIEW

**Comment by afzalsayed96** [comment]
@chaance We're seeing a lot of warnings in our codebase because of unplaced refs. The problem is our component renders a part of logic conditionally, which contains the target element. When we're not rendering that part of logic, we're making sure observe is set to false, but the warning doesn't consider that.

Is there any chance you'll reconsider this PR?

PS: Test failed due to npm being down when PR was created (https://twitter.com/npmstatus/status/1291296875572629504)

**Comment by afzalsayed96** [comment]
Hey @chaance,
Could you take a second look at this? Have resolved the type errors.
Thanks

**Comment by afzalsayed96** [comment]
Yo! Just checking if there's anything I can do to get this merged in.

**Comment by afzalsayed96** [comment]
Thanks for merging in! When can we expect a release?

**Comment by chaance** [comment]
Hoping for this weekend. Trying to get a couple of bugs fixed first if I can. In the mean time there's always [`patch-package`](https://www.npmjs.com/package/patch-package) if you need it sooner!

**Comment by afzalsayed96** [comment]
Thanks a lot! Got a bit scared there after seeing the older warning replaced by a newer deprecation warning after update 😅 

Screenshot 2021-08-02 at 12 25 13 PM

The console is finally clear of warnings after making the suggested change :phew:

**Pull request merged**
