### PR TITLE
component-component tests

### PR DESCRIPTION
**Pull request by jakierice**
@ryanflorence, I wanted to go ahead and open this PR to get some feedback on what I've done so far. There are a few things that I am not real sure about at this point, and I don't wanna travel too far down a faulty path.

I'm not entirely sure how to approach testing the state changes or lifecycle function props using snapshots alone. I am definitely willing to keep going if you have some suggestions of how to assert that type of functionality from final renders.

Please let me know what you think, and I will adjust course as need be.

### CODE REVIEW

**Comment by jakierice** [comment]
Ok, cool. I will work along those lines and push those changes. Thanks for the feedback.

**Comment by jakierice** [comment]
@ryanflorence still working on the `<Component>` tests. Heading out for some family time for the rest of the day, but I didn't want you to think I've given up. I'm hoping to finish them out tomorrow. Let me know if you see anything glaringly wrong with it so far.

**Comment by jakierice** [comment]
Thank you! This should be good to go now. Let me know if there are any changes you would like me to make. I look forward to getting your feedback.

**Comment by jakierice** [comment]
@ryanflorence not sure if you were notified for my last comment because I didn't tag you. I just wanted to make sure that you saw it.

**Comment by jakierice** [comment]
@ryanflorence I just wanted to check in and see if there is anything else I need to do here for the tests. If these look good to you, and you decide to merge them in, I can definitely start preparing to write tests for the other components.

If it would be better, I can close this PR and open a new one. Let me know what you think.

**Comment by ryanflorence** [comment]
Hey @jakierice, sorry for the long delay, I'm back at OSS again after a bunch of workshops.

Can you rebase squash all of your commits into one and force push again? Thanks!

**Comment by jakierice** [comment]
@ryanflorence, no problem. Welcome back! The commit history is pretty messy because I was just merging master back in to keep things up to date. So even if I squash my commits, they'll still be sprinkled throughout. I can "squash and merge" back into master, or I can blow out this branch and point the PR from a new branch with a clean commit history. Thoughts?

**Comment by ryanflorence** [comment]
Yeah I'd like to merge this stuff as just one commit.

**Comment by ryanflorence** [comment]
It's a good git workout 😝, thanks!

**Pull request merged**
